############################################################################################################
##
## Summarize multi-channel intensity measurements from segmented cells of 
## individual tissue sections generated by the FIJI Macro
##
## Notes:
##
## - Script and quantification were developed for 16-bit images captured on a 
##   Zeiss AxioObserver.Z1 with ApoTome.2 and experiment-specific exposure times
## - Customization/optimization of intensity cutoffs for DAPI, PIWI-1, and prog-1 (red signal),
##   parameters for renaming/shortening filenames, etc. may be necessary for other experiments
##     
############################################################################################################

## load packages
library(stringr)
library(ggplot2)
library(patchwork)
library(dplyr)

## set directory to .csv files for compilation
setwd("~/your/directory/here")

## set up: create file list, create folder for plots, create empty data frame
csv_files = list.files(pattern ="data") #choose files containing data in the name
dir.create("../PlotsFromR") #this create a folder in the designated directory
all_results = data.frame() #create data frame for results

## loop to process all csv files

# This loop will iterate through all the listed csv files
# This loop assumes that the files are in this order: dapi, piwi, red
# If not, change the order below

for (i in seq(from=1, to = length(csv_files), by = 3)){
  dapi =read.csv(csv_files[i]) #this reads the i file
  piwi =read.csv(csv_files[i+1]) #this reads the i+1 file
  red =read.csv(csv_files[i+2]) #this reads the i+2 file

  # change column names of object dapi, piwi, red etc
  colnames(dapi)[c(1,4)] = c("Cell","Mean_Fluor_Dapi")
  colnames(piwi)[c(1,4)] = c("Cell","Mean_Fluor_Piwi")
  colnames(red)[c(1,4)] = c("Cell","Mean_Fluor_Red")
  
  # this function extracts columns 1 to 4 from object, and keeps all the rows
  dapi = dapi[,1:4]
  piwi = piwi[,1:4]
  red = red[,1:4]
  
  # $Label select the column named Label and convert it to ...using str_replace(); keep string except after -Apo
  dapi$Label = str_replace(dapi$Label, "(.*)-Apo.*", "\\1")
  piwi$Label = str_replace(piwi$Label, "(.*)-Apo.*", "\\1")
  red$Label = str_replace(red$Label, "(.*)-Apo.*", "\\1")
  
  merge_colors = merge(dapi, piwi, sort = F) #set sort to false
  merge_colors = merge(merge_colors, red, sort = F)
  
  #merge_colors[order(merge_colors$Cell)] #order function returns numeric row order

  # set image quantification cutoffs and bin cells
  Dapi_cutoff = 100 #set Dapi cutoff
  merge_colors$Dapi_Pos = merge_colors$Mean_Fluor_Dapi > Dapi_cutoff
  merge_colors$Dapi_Pos = factor(merge_colors$Dapi_Pos, levels = c(TRUE, FALSE)) #assign level to Dapi_Pos to ensure True comes before False when plotting
  
  Piwi_Hi_cutoff = 1300 #set values based on empirical examination and the relative proportions of PIWI-Hi and PIWI-Lo cells in controls
  Piwi_Lo_cutoff = 300 

  merge_colors$Piwi_Status = "Piwi_Lo"
  merge_colors$Piwi_Status[merge_colors$Mean_Fluor_Piwi < Piwi_Lo_cutoff] = "Piwi_Neg"
  merge_colors$Piwi_Status[merge_colors$Mean_Fluor_Piwi > Piwi_Hi_cutoff] = "Piwi_Hi"
  merge_colors$Piwi_Status = factor(merge_colors$Piwi_Status, levels = c("Piwi_Hi", "Piwi_Lo", "Piwi_Neg"))
  
  Red_cutoff = 400 #set Red cutoff based on empirical examination composite mask image
  merge_colors$Red_Pos = merge_colors$Mean_Fluor_Red > Red_cutoff
  merge_colors$Red_Pos = factor(merge_colors$Red_Pos, levels = c(TRUE, FALSE))
  
  merge_colors$Dapi_Red_Pos = NA
  merge_colors$Dapi_Red_Pos[merge_colors$Dapi_Pos == TRUE & merge_colors$Red_Pos == TRUE] = "Dapi+_Red+"
  merge_colors$Dapi_Red_Pos[merge_colors$Dapi_Pos == FALSE & merge_colors$Red_Pos == TRUE] = "Dapi-_Red+"
  merge_colors$Dapi_Red_Pos[merge_colors$Dapi_Pos == TRUE & merge_colors$Red_Pos == FALSE] = "Dapi+_Red-"
  merge_colors$Dapi_Red_Pos[merge_colors$Dapi_Pos == FALSE & merge_colors$Red_Pos == FALSE] = "Dapi-_Red-"
  merge_colors$Dapi_Red_Pos = factor(merge_colors$Dapi_Red_Pos,
                                     levels = c("Dapi+_Red+", "Dapi+_Red-","Dapi-_Red+", "Dapi-_Red-"))
  
  hist(log10 (merge_colors$Mean_Fluor_Piwi), breaks = 200) #look at PIWI-1 labeling distribution, file not saved
  
  # this block generates 5 scatter plots to show the distribution of particles with various labeling characteristics
  Sample_Name = merge_colors$Label[1] 
  
  Piwi_Plot = ggplot(data = merge_colors, aes(x = Area, y = Mean_Fluor_Piwi, color = Piwi_Status)) +
    geom_point() +  #makes a scatter plot
    scale_y_continuous(trans = 'log10') + 
    ggtitle(Sample_Name)
  
  Riboprobe_Plot = ggplot(data = merge_colors, aes(x = Area, y = Mean_Fluor_Red, color = Red_Pos)) +
    geom_point() + 
    scale_y_continuous(trans = 'log10') +
    ggtitle(Sample_Name)
  
  Dapi_Plot = ggplot(data = merge_colors, aes(x = Area, y = Mean_Fluor_Dapi, color = Dapi_Pos)) +
    geom_point() +
    scale_y_continuous(trans = 'log10') +
    ggtitle(Sample_Name)
  
  Dapi_Riboprobe_Plot = ggplot(data = merge_colors, aes(x = Mean_Fluor_Dapi, y = Mean_Fluor_Red, color = Dapi_Red_Pos)) +
    scale_color_manual(values = c("purple","blue","red","yellow"))+
    geom_point() + 
    geom_hline(yintercept = Red_cutoff, linetype="dashed", color = "black") +
    annotate(geom = "text", x = 0, y = Red_cutoff, label= Red_cutoff, vjust=-1, color="black")+
    scale_y_continuous(trans = 'log10') +
    ggtitle(Sample_Name)
  
  Piwi_Riboprobe_Plot = ggplot(data = merge_colors, aes(x = Mean_Fluor_Piwi, y = Mean_Fluor_Red, color = Piwi_Status)) + 
    geom_point() + 
    geom_hline(yintercept = Red_cutoff, linetype="dashed", color = "black") +
    annotate(geom = "text", x = 0, y = Red_cutoff, label= Red_cutoff, vjust=-1, color="black")+
    scale_y_continuous(trans = 'log10') +
    ggtitle(Sample_Name)

  pdf(paste0("../PlotsFromR/",Sample_Name,"_Plots.pdf"), width = 20)
  print(Dapi_Plot + Riboprobe_Plot + Piwi_Plot + Dapi_Riboprobe_Plot + Piwi_Riboprobe_Plot)
  dev.off()
  
  write.csv(merge_colors, file = paste0("merged_table_",dapi$Label[1], ".csv"), row.names = FALSE) #this code create a merged table for each of the samples  
  
  all_results = rbind(all_results,merge_colors)
  
}

## This block generates and writes summary statistics tables - for export to Prism, etc.
true_cells = all_results[all_results$Dapi_Pos == TRUE,] 

Stat_Table = 
  true_cells  %>% group_by(Label) %>% summarize(NumDapi = n(),
                                                NumRed = sum(Red_Pos == TRUE),
                                                PercentRed = (NumRed/NumDapi)*100,
                                                NumPiwiHi = sum(Piwi_Status == "Piwi_Hi"),
                                                PercentPiwiHi = (NumPiwiHi/NumDapi)*100,
                                                NumPiwiLo = sum(Piwi_Status == "Piwi_Lo"),
                                                PercentPiwiLo = (NumPiwiLo/NumDapi)*100,
                                                NumPiwiNeg = sum(Piwi_Status == "Piwi_Neg"),
                                                PercentPiwiNeg = (NumPiwiNeg/NumDapi)*100,
                                                Red_Piwi_Hi = sum(Red_Pos == TRUE & Piwi_Status == "Piwi_Hi"),
                                                Percent_Red_Piwi_Hi = Red_Piwi_Hi/NumRed*100,
                                                Red_Piwi_Lo = sum(Red_Pos == TRUE & Piwi_Status == "Piwi_Lo"),
                                                Percent_Red_Piwi_Lo = Red_Piwi_Lo/NumRed*100,
                                                Red_Piwi_Neg = sum(Red_Pos == TRUE & Piwi_Status == "Piwi_Neg"),
                                                Percent_Red_Piwi_Neg = Red_Piwi_Neg/NumRed*100
  )


write.csv(Stat_Table, file = "Summary_Statistics.csv", row.names = FALSE) # create the Summary_Statistics.csv file

true_red_cell = all_results[all_results$Red_Pos == TRUE & all_results$Dapi_Pos == TRUE,] #This block generates the average area of the red cells and the mean Fluor of the red cells

Ave_Red_Cell_Area =
  true_red_cell %>% group_by(Label) %>% summarize(RedCell = sum(Red_Pos == TRUE),
                                                  RedCellArea = mean(Area),
                                                  RedCellIntensity = mean(Mean_Fluor_Red)
  )

write.csv(Ave_Red_Cell_Area, file = "Area_Summary_Statistics.csv", row.names = FALSE)

## sessionInfo

sessionInfo()

R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
  [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
  [1] dplyr_1.0.7     patchwork_1.1.1 ggplot2_3.3.5   stringr_1.4.0  

loaded via a namespace (and not attached):
  [1] rstudioapi_0.13     magrittr_2.0.1      usethis_2.0.1       tidyselect_1.1.1    munsell_0.5.0       colorspace_2.0-2   
[7] R6_2.5.1            rlang_0.4.11        fansi_0.5.0         tools_4.1.1         grid_4.1.1          gtable_0.3.0       
[13] utf8_1.2.2          cli_3.0.1           DBI_1.1.2           withr_2.4.2         ellipsis_0.3.2      digest_0.6.27      
[19] assertthat_0.2.1    tibble_3.1.4        lifecycle_1.0.0     crayon_1.4.1        farver_2.1.0        BiocManager_1.30.16
[25] purrr_0.3.4         vctrs_0.3.8         fs_1.5.0            glue_1.4.2          labeling_0.4.2      stringi_1.7.4      
[31] compiler_4.1.1      pillar_1.6.2        generics_0.1.0      scales_1.1.1        pkgconfig_2.0.3   


